### ISSUE TITLE
burpsuite2024.9添加插件报错

### ISSUE THREAD

**Issue by 1156494497** [sule01u/AutorizePro#4]
burpsuit 2024.9版本 添加python报错
java.lang.NoClassDefFoundError: com/google/common/collect/MapMaker
	at org.python.core.ThreadStateMapping.<clinit>(ThreadStateMapping.java:31)
	at org.python.core.Py.<clinit>(Py.java:1750)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:99)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:93)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:70)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at burp.Zbmh.ZE(Unknown Source)
	at burp.Zpta.Zk(Unknown Source)
	at burp.Zpg3.ZQ(Unknown Source)
	at burp.Zktm.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at

**Comment by sule01u** [comment]
你的java版本是多少？

**Comment by 1156494497** [comment]
java 21  jython2.7.3

**Comment by sule01u** [comment]
你用java1.8试试看

**Comment by 1156494497** [comment]
新版本的burp已经不支持java 1.8

**Comment by sule01u** [comment]
工具运行的测试环境就是burp suite 2024.9 , jython 2.7.3; 
除了系统java版本不一致，我的版本是1.8，你可以试试比java21低的版本；这个跟工具本身应该没影响；

**Comment by sule01u** [comment]
不好意思，我之前的回答有误，我测试时候用的是burp suite 2024.9 自带的java版本，我们环境应该是一致的。
1. 确保 Guava 库存在

	•	检查 JAR 文件：
	•	检查 Burp 的运行环境中是否包含 guava-x.x.x.jar。
	•	在你的 Burp 安装目录中寻找 lib 或 resources 文件夹，确保存在 Guava JAR 文件。
	•	如果缺失，可以从 [Maven Repository](https://mvnrepository.com/artifact/com.google.guava/guava) 下载最新版本的 Guava JAR。
	•	将 Guava 添加到 ClassPath：
	•	如果手动运行 Burp，确保启动命令中包含：
`java -cp "path/to/guava-x.x.x.jar:other/dependencies" burp.StartBurp`

2. 升级 Guava 库版本

	•	如果 Guava 已存在但版本较旧，升级到 兼容版本（比如最新稳定版本）。
	•	推荐版本：guava-31.1-jre 或更高。

**Comment by 1156494497** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
